apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: u66tom710-python
  janus-idp.io/tekton: u66tom710-python
  backstage.io/kubernetes-id: u66tom710-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: u66tom710-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
