apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: u66tom710-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: u66tom710-python 
  name: u66tom710-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: u66tom710-python 
