apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: u66tom710-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-eee46d8e79.cdja.p3.openshiftapps.com/rhtap/rhtap-qe:434878f5a079e58638ac79c45c5a5bffe21bfd1e@sha256:c429de6b94ccd11656d8056380f483401cc15715859112c2d6d81cfcfb2ac5b2
          name: container-image
